name: Tag with PostgreSQL versions
on:
  workflow_dispatch:
    inputs: {}
  schedule:
    - cron: '0 0 * * 1'
jobs:
  tag:
    runs-on: ubuntu-latest
    environment: pull-tags
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Run AWS CLI command
        run: |
          aws rds describe-db-engine-versions --region eu-central-1 --engine postgres --engine-version 14 --query "DBEngineVersions[*].{version:EngineVersion}" --output json > versions.json
      - run: echo "previous_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo '')" >> $GITHUB_ENV
      - name: Create Tag
        id: create_tag
        uses: jaywcjlove/create-tag-action@v1.3.18
      #  if: env.previous_tag
        with:
          package-path: ./versions.json
